from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'


BIG_FONT_SIZE = 35
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 16
TEXT_MARGIN = 20
MINIMUM_WIDTH = 600
